global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "proxy_server"
    static_configs:
      - targets: ["proxy_server:3002"]
    metrics_path: /metrics

  - job_name: "unstable_backend"
    static_configs:
      - targets: ["unstable_backend:3001"]
    metrics_path: /metrics

  - job_name: "load_test"
    static_configs:
      - targets: ["host.docker.internal:9091"]
    metrics_path: /metrics
    scrape_interval: 5s
