{
 "title": "Opossum Monitoring",
 "tags": [
  "opossum",
  "circuit-breaker",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Circuit Breaker State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "circuit_breaker_state{name=\"backendCircuit\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Circuit Breaker Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(circuit_breaker_events_total[1m])"
    }
   ]
  }
 ]
}